import type {
  StorefrontCategory,
  StorefrontConfig,
  StorefrontProduct,
} from "./types";

export const defaultStorefrontConfig: StorefrontConfig = {
  brandName: "Nextech Malta",
  logoPath: "/nextech-logo.png",
  primaryColor: "#2590a4",
  announcementEnabled: true,
  announcementText: "Free Malta delivery on orders over €100",
  announcementButton: "SHOP NOW",
  announcementLink: "#shop",
  navigation: { shop: "Shop", prebuilt: "Prebuilt PCs", contact: "Contact" },
  cart: {
    label: "Cart",
    enquiryLabel: "Send cart enquiry",
    continueLabel: "Continue shopping",
    emptyTitle: "Your cart is empty.",
    emptyBody: "Great hardware is only a click away.",
  },
  hero: {
    eyebrow: "Built in Malta. Built for you.",
    lineOne: "YOUR NEXT",
    accent: "LEVEL",
    lineTwo: "STARTS HERE.",
    body: "High-performance custom PCs, premium components and gear—expertly selected and supported locally.",
    primaryButton: "Shop the latest",
    secondaryButton: "Build your PC",
    trustPoints: ["2-year warranty", "Local support", "Personal service"],
    cardLabel: "NEX SERIES",
    cardTitle: "Performance without compromise.",
    cardLink: "Engineered in Malta →",
  },
  shop: {
    eyebrow: "Hand-picked hardware",
    heading: "LEVEL UP YOUR SETUP.",
    viewAll: "View all products →",
    typesLabel: "PRODUCT TYPES",
    searchPlaceholder: "Search products",
    addButton: "Add to cart",
    scrollHint: "Scroll sideways to view more products",
  },
  build: {
    eyebrow: "Personalised PC service",
    headingOne: "YOUR PC.",
    headingTwo: "YOUR WAY.",
    body: "Tell us what you play, create or stream and your approximate budget. A Nextech specialist will contact you directly to recommend the right personalised build.",
    steps: [
      "Send your requirements",
      "Speak to a specialist",
      "We build & test",
    ],
    button: "Start your build enquiry",
  },
  services: [
    {
      title: "Expert guidance",
      body: "Real advice from PC enthusiasts—not a generic sales desk.",
      icon: "◈",
    },
    {
      title: "Built & tested locally",
      body: "Careful assembly, clean cable management and full stability testing.",
      icon: "⚙",
    },
    {
      title: "Malta-wide delivery",
      body: "Fast delivery across Malta and Gozo, or collect by arrangement.",
      icon: "↗",
    },
  ],
  contact: {
    eyebrow: "Talk to Nextech",
    headingOne: "LET’S BUILD",
    headingTwo: "SOMETHING GREAT.",
    body: "Need a personalised PC or help choosing a component? Send us your details and our team will get back to you directly.",
    directLabel: "Prefer to contact us directly?",
    submitButton: "Send enquiry",
    helperText: "Contact submissions will be enabled in Milestone 5.",
    email: "info@nextechmt.com",
    phoneOne: "+356 7762 1122",
    phoneTwo: "+356 7739 6178",
    location: "Malta · Online & by appointment",
  },
  footer: {
    callLabel: "CALL / WHATSAPP",
    emailLabel: "EMAIL US",
    linksLabel: "QUICK LINKS",
    shopLink: "Shop",
    buildLink: "Custom build enquiry",
    adminLink: "Admin login",
    copyright: "© 2026 Nextech Malta. Development storefront.",
    privacyLabel: "Privacy",
    termsLabel: "Terms",
    deliveryLabel: "Delivery & returns",
  },
};

export const defaultStorefrontCategories: StorefrontCategory[] = [
  "All products",
  "Prebuilt PCs",
  "Motherboards",
  "Graphic Cards",
  "Processors",
  "RAMs",
  "Storage",
  "Cooling",
  "Cases",
  "Peripherals",
].map((name, index) => ({
  id: `development-category-${index}`,
  slug: name.toLowerCase().replaceAll(" ", "-"),
  name,
  displayOrder: index,
}));

const developmentProducts = [
  [
    "NEX Aether RTX 5070",
    "Prebuilt PCs",
    189900,
    204900,
    "Featured",
    "Ryzen 7 · RTX 5070 · 32GB DDR5",
  ],
  [
    "GeForce RTX 5070 12GB",
    "Graphic Cards",
    72900,
    null,
    "New",
    "GDDR7 · Triple-fan cooling",
  ],
  [
    "Ryzen 7 9800X3D",
    "Processors",
    58900,
    null,
    "Top seller",
    "8 cores · AM5 · Gaming CPU",
  ],
  [
    "NEX Pulse 75 Keyboard",
    "Peripherals",
    9990,
    11990,
    "Sale",
    "Hot-swap · Wireless · RGB",
  ],
  [
    "Arctic 360 A-RGB",
    "Cooling",
    12900,
    null,
    "In stock",
    "360mm liquid CPU cooler",
  ],
  [
    '27" QHD 180Hz Display',
    "Peripherals",
    27900,
    null,
    "Great value",
    "IPS · 1ms · Adaptive Sync",
  ],
  [
    "B650 Gaming WiFi",
    "Motherboards",
    18900,
    null,
    "In stock",
    "AM5 · DDR5 · Wi-Fi 6E",
  ],
  [
    "NEX Glide Wireless Mouse",
    "Peripherals",
    6490,
    null,
    "New",
    "26K DPI · 59g · Tri-mode",
  ],
  [
    "2TB Gen4 NVMe SSD",
    "Storage",
    13400,
    null,
    "In stock",
    "7,400MB/s · PCIe 4.0",
  ],
  [
    '34" Ultrawide 165Hz',
    "Peripherals",
    42900,
    null,
    "Featured",
    "WQHD · Curved · USB-C",
  ],
  [
    "NEX Nova RTX 5060 Ti",
    "Prebuilt PCs",
    129900,
    null,
    "Popular",
    "Ryzen 5 · RTX 5060 Ti · 32GB",
  ],
  [
    "Dual Tower Air Cooler",
    "Cooling",
    5490,
    null,
    "Great value",
    "6 heatpipes · Dual 120mm fans",
  ],
  [
    "32GB DDR5 6000MHz Kit",
    "RAMs",
    10900,
    null,
    "In stock",
    "2×16GB · CL30 · EXPO",
  ],
  [
    "NEX Airflow M2 Case",
    "Cases",
    8990,
    null,
    "New",
    "Tempered glass · 4 ARGB fans",
  ],
] as const;

/** Development-only fallback rows. Production storefronts must use database rows. */
export const developmentSeedProducts: StorefrontProduct[] =
  developmentProducts.map(
    (
      [name, categoryName, priceMinor, oldPriceMinor, tag, shortSpec],
      index,
    ) => ({
      id: `development-product-${index + 1}`,
      categoryId: `development-category-${defaultStorefrontCategories.findIndex((category) => category.name === categoryName)}`,
      categorySlug: categoryName.toLowerCase().replaceAll(" ", "-"),
      categoryName,
      name,
      slug: name
        .toLowerCase()
        .replaceAll(/[^a-z0-9]+/g, "-")
        .replace(/^-|-$/g, ""),
      sku: `NEX-DEV-${String(index + 1).padStart(3, "0")}`,
      shortSpec,
      priceMinor,
      oldPriceMinor,
      currencyCode: "EUR",
      tag,
      displayOrder: index,
    }),
  );
